username = prompt('请驶入姓名')
age = prompt('请输入年龄')
gender = prompt('请输入性别')
// document.write(<h1>姓名：username</h1>)
console.log(username)
console.log(age)
console.log(gender)

document.write(username,'\n')
document.write(age)
document.write(gender)
